services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
        ollama serve &
        sleep 5
        # Pull the default model needed for the agentic RAG system
        echo "Pulling $OLLAMA_MODEL"
        ollama pull "$OLLAMA_MODEL"
        echo "All models pulled successfully!"
        wait
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3-chatqa:8b}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s  # Increased to allow time for model downloads


networks:
  default:
    name: agentic-rag

volumes:
  ollama_data:
