# Create your compose file. To learn more, please visit
# https://docs.docker.com/reference/compose-file/
services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
  etcd:
    image: bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd
    restart: unless-stopped
  milvus:
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "standalone"]
    runtime: nvidia
    platform: linux/arm64
    environment:
      # Milvus connects to the internal etcd service by default.
      # Override ETCD_ENDPOINTS if you want to use a different instance.
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS:-http://etcd:2379}

    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    restart: unless-stopped
      
networks:
  default:
    name: agentic-rag

volumes:
  ollama_data:
  milvus_data:
  etcd_data:
