# Create your compose file. To learn more, please visit
# https://docs.docker.com/reference/compose-file/
services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
  milvus:
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "standalone"]
    runtime: nvidia
    platform: linux/arm64
    environment:
      # Use an external etcd instance by providing its endpoint. Do not use
      # localhost here because it resolves inside the container.  If this
      # variable is empty, Milvus defaults to its embedded etcd.
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS:-}
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    restart: unless-stopped
      
networks:
  default:
    name: agentic-rag

volumes:
  ollama_data:
  milvus_data:
