services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
        ollama serve &
        sleep 5
        ollama pull ${OLLAMA_MODEL:-llama3:8b-instruct}
        wait
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3:8b-instruct}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  etcd:
    image: bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/bitnami/etcd
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    command: server /data/minio --console-address :9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data/minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "standalone"]
    # Remove conflicting runtime and platform specs
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      # Add these important environment variables
      MINIO_ACCESS_KEY_ID: minio
      MINIO_SECRET_ACCESS_KEY: minio123
      MINIO_USE_SSL: "false"
      # Common config overrides
      common.defaultPartition: "_default"
      common.defaultIndexName: "_default_idx"
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    restart: unless-stopped
    depends_on:
      etcd:
        condition: service_started
      minio:
        condition: service_healthy
      ollama:
        condition: service_healthy

networks:
  default:
    name: agentic-rag

volumes:
  ollama_data:
  milvus_data:
  etcd_data:
  minio_data: